# NB: copied from an enkore project because we are using fourtune here...
# NB: has been adjusted to work with fourtune

name: Setup private key, certificate and access tokens

inputs:
  anio-pkey:
    required: true
  anio-cert:
    required: true
  anio-registry-token:
    required: true
  npm-token:
    required: true

runs:
  using: "composite"
  steps:
    # Place private key and certificate in order to have
    # access to npm-registry.anio.software
    - name: "Setup runner private key and certificate"
      shell: bash
      run: |
        mkdir ./secrets/
        chmod 0700 ./secrets/

        touch ./secrets/npm_client.pkey
        touch ./secrets/npm_client.cert
        touch ./secrets/anio_npm_auth_token
        touch ./secrets/npm_auth_token

        chmod 0600 ./secrets/npm_client.pkey
        chmod 0600 ./secrets/npm_client.cert
        chmod 0600 ./secrets/anio_npm_auth_token
        chmod 0600 ./secrets/npm_auth_token

        printf "%s" "${{ inputs.anio-pkey }}" > ./secrets/npm_client.pkey
        printf "%s" "${{ inputs.anio-cert }}" > ./secrets/npm_client.cert

        printf "//npm-registry.anio.software/:_authToken=%s\n" "${{ inputs.anio-registry-token }}" >> .npmrc
        printf "//registry.npmjs.org/:_authToken=%s\n" "${{ inputs.npm-token }}" >> .npmrc

        openssl x509 -in ./secrets/npm_client.cert -noout -text

        ls -la ./secrets/
