import {
	type EnkoreLockFile,
	type ValidToolchainCombinations,
	readEntityJSONFile,
	createEntity
} from "@enkore/spec"
import {_debugPrint} from "./_debugPrint.mts"
import {getEnkoreLockFilePath} from "./paths/getEnkoreLockFilePath.mts"
import {isFileSync, writeAtomicFileJSON} from "@aniojs/node-fs"

export async function _readLockFileOrCreateIt(
	projectRoot: string,
	toolchain: ValidToolchainCombinations
): Promise<EnkoreLockFile> {
	_debugPrint("_readLockFileOrCreateIt called")

	const lockfilePath = getEnkoreLockFilePath(projectRoot)

	//
	// i know this is racy
	// (checking and then creating the file if it doesn't exist)
	//
	if (isFileSync(lockfilePath)) {
		_debugPrint(`enkore-lock.json file exists`)

		return await readEntityJSONFile(
			lockfilePath, "EnkoreLockFile", 0, 0
		)
	}

	const lockfileData = createEntity("EnkoreLockFile", 0, 0, {
		toolchain,
		autogeneratedFiles: {}
	})

	await writeAtomicFileJSON(lockfilePath, lockfileData, {pretty: true})

	_debugPrint(`i have created an empty enkore-lock.json file`)

	return lockfileData
}
