import type {TargetIdentifier} from "@enkore/spec/primitives"
import {
	createEntity,
	readEntityJSONFile,
	type EnkoreLockFile
} from "@enkore/spec"
import {
	isFileSync,
	writeAtomicFileJSON
} from "@aniojs/node-fs"
import {getEnkoreLockFilePath} from "#~src/internal/paths/getEnkoreLockFilePath.mts"
import {_debugPrint} from "./_debugPrint.mts"

export async function _readLockFileOrCreateIt(
	projectRoot: string, targetIdentifier: TargetIdentifier
): Promise<EnkoreLockFile> {
	_debugPrint("_readLockFileOrCreateIt called")

	const lockfilePath = getEnkoreLockFilePath(projectRoot)

	//
	// i know this is racy
	// (checking and then creating the file if it doesn't exist)
	//
	if (isFileSync(lockfilePath)) {
		return await readEntityJSONFile(
			lockfilePath, "EnkoreLockFile", 0, 0
		)
	}

	const lockfileData = createEntity("EnkoreLockFile", 0, 0, {
		targetIdentifier,
		targetDependencies: {},
		targetDependenciesStamp: "",
		autogeneratedFiles: {}
	})

	await writeAtomicFileJSON(lockfilePath, lockfileData, {pretty: true})

	_debugPrint(`i have created an empty enkore-lock.json file`)

	return lockfileData
}
