import {
	type EnkoreConfig,
	type ValidToolchainCombinations
} from "@enkore/spec"
import {readLockFile} from "./readLockFile.mts"
import {_writeLockFile} from "./_writeLockFile.mts"
import {log} from "@enkore/debug"

export async function _updateLockFileToolchain(
	projectRoot: string,
	toolchain: ValidToolchainCombinations
) {
	log("_updateLockFileToolchain called")

	//
	// we presume the enkore-lock.json file exists here
	// it should have been created by initializeProject() if it
	// didn't exist before (NB: only in non-CI mode of course)
	//
	const currentLockFileData = await readLockFile(projectRoot)

	await _writeLockFile(projectRoot, {
		autogeneratedFiles: currentLockFileData.autogeneratedFiles,
		toolchain
	})
}
