import {writeAtomicFileJSON} from "@aniojs/node-fs"
import {getEnkoreLockFilePath} from "./paths/getEnkoreLockFilePath.mts"
import {
	readEntityJSONFile,
	type EnkoreConfig,
	type EnkoreLockFile
} from "@enkore/spec"
import type {InstalledDependency} from "./installRealmDependencies/InstalledDependency.d.mts"

export async function updateLockFile(
	projectRoot: string,
	projectConfig: EnkoreConfig,
	installedDependencies: InstalledDependency[],
	targetDependenciesStamp: string
) {
	const lockFilePath = getEnkoreLockFilePath(projectRoot)

	const currentLockFileData = await readEntityJSONFile(lockFilePath, "EnkoreLockFile", 0, 0, {
		targetIdentifier: projectConfig.target._targetIdentifier,
		autogeneratedFiles: {},
		targetDependencies: {},
		targetDependenciesStamp: ""
	})

	currentLockFileData.targetIdentifier = projectConfig.target._targetIdentifier

	let targetDependencies : EnkoreLockFile["targetDependencies"] = {}

	for (const dependency of installedDependencies) {
		targetDependencies[dependency.name] = {
			version: dependency.version,
			requestedVersion: dependency.requestedVersion
		}
	}

	await writeAtomicFileJSON(
		lockFilePath, {
			...currentLockFileData,
			targetDependencies,
			targetDependenciesStamp
		}, {pretty: true}
	)
}
