import {writeAtomicFileJSON} from "@aniojs/node-fs"
import {getEnkoreLockFilePath} from "./paths/getEnkoreLockFilePath.mts"
import {
	readEntityJSONFile,
	type EnkoreConfig,
	type EnkoreLockFile
} from "@enkore/spec"
import type {InstalledDependency} from "./installRealmDependencies/InstalledDependency.d.mts"

export async function updateLockFile(
	projectRoot: string,
	projectConfig: EnkoreConfig,
	installedDependencies: InstalledDependency[],
	realmDependenciesStamp: string
) {
	const lockFilePath = getEnkoreLockFilePath(projectRoot)

	const currentLockFileData = await readEntityJSONFile(lockFilePath, "EnkoreLockFile", 0, 0, {
		realm: projectConfig.realm.name,
		autogeneratedFiles: {},
		realmDependencies: {},
		realmDependenciesStamp: ""
	})

	currentLockFileData.realm = projectConfig.realm.name

	let realmDependencies : EnkoreLockFile["realmDependencies"] = {}

	for (const dependency of installedDependencies) {
		realmDependencies[dependency.name] = {
			version: dependency.version,
			requestedVersion: dependency.requestedVersion
		}
	}

	await writeAtomicFileJSON(
		lockFilePath, {
			...currentLockFileData,
			realmDependencies,
			realmDependenciesStamp
		}, {pretty: true}
	)
}
