import {readLockFile} from "./readLockFile.ts"
import {_writeLockFile} from "./_writeLockFile.ts"
import type {EnkoreLockFile} from "@anio-software/enkore-private.spec"

export async function _updateLockfileAutogeneratedFiles(
	projectRoot: string,
	files: {
		[path: string]: {
			hash: string
		}
	}
): Promise<EnkoreLockFile> {
	const currentLockFile = await readLockFile(projectRoot)

	currentLockFile.autogeneratedFiles = files

	await _writeLockFile(projectRoot, currentLockFile)

	return currentLockFile
}
