import {readLockFile} from "./readLockFile.ts"
import {_writeLockFile} from "./_writeLockFile.ts"

export async function _updateLockfileAutogeneratedFiles(
	projectRoot: string,
	files: {
		[path: string]: {
			hash: string
		}
	}
): Promise<undefined> {
	const currentLockFile = await readLockFile(projectRoot)

	currentLockFile.autogeneratedFiles = files

	await _writeLockFile(projectRoot, currentLockFile)

	return undefined
}
